### ISSUE TITLE
term_id -> term_label

### ISSUE THREAD

**Issue by sveinugu** [fairtracks/fairtracks_augment#2]
- Each `term_label` is sibling to a `term_id` containing URLs which works as identifiers in an OWL ontology file.
- The URL to the OWL ontology files can be found in the FAIRtracks JSON schema under `term_id->ontology`
- [x] Fetch the ontology information for each `term_id` (either manually or automatically)
- [x] Download the OWL files locally (once per day?)
- [x] For each `term_id`, fetch the label from the OWL and store into `term_value`.

**Comment by sveinugu** [comment]
Idea for code architecture:

```
handleElement(element, path):
    if 'term_id' in element:
        # term_id -> term_value
    if path == someHardcodedPath:
        # handle it...
    if element is list or dict:
       for x in element:
          handleElement(x, path+x)
```

**Comment by radmilak** [comment]
done
