### ISSUE TITLE
Fetch species_name from taxonomy curie

### ISSUE THREAD

**Issue by sveinugu** [fairtracks/fairtracks_augment#5]
`samples->species_id` is a CURIE that is resolvable from http://identifiers.org. Fetch the species name from the resulting taxonomy database (which is hardcoded to https://www.ncbi.nlm.nih.gov/Taxonomy) and return in `samples->species_name`.

**Comment by radmilak** [comment]
@sveinugu I implemented this, though for each taxonomy database there will have to be a separate solution for how to actually get the species_name, as there seems to be no standard for this. So for now it will only work with ncbi.

**Comment by sveinugu** [comment]
NCBI is the only one supported by FAIRtracks standard, so that is ok. Any pull requests or commits?
